apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: course-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: learning-platform
  
  source:
    repoURL: https://github.com/yourorg/learning-platform.git
    targetRevision: main
    path: kubernetes/helm-charts/course-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: "123456789012.dkr.ecr.us-east-1.amazonaws.com/learning-platform/course-service"
        - name: image.tag
          value: "latest"
        - name: replicaCount
          value: "2"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: learning-platform-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
